# Generated by Django 6.0.3 on 2026-03-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='category_name', max_length=40)),
                ('descripcion', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(db_column='customer_id', max_length=5, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='company_name', max_length=40)),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, db_column='contact_title', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=60, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=24, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=24, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='employee_id', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='last_name', max_length=20)),
                ('first_name', models.CharField(db_column='first_name', max_length=10)),
                ('title', models.CharField(blank=True, db_column='title', max_length=30, null=True)),
                ('title_of_courtesy', models.CharField(blank=True, db_column='title_of_courtesy', max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, db_column='birth_date', null=True)),
                ('hire_date', models.DateField(blank=True, db_column='hire_date', null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=60, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, db_column='home_phone', max_length=24, null=True)),
                ('extension', models.CharField(blank=True, db_column='extension', max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, db_column='photo', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('photo_path', models.CharField(blank=True, db_column='photo_path', max_length=255, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, db_column='employee_id', null=True)),
                ('order_date', models.DateField(blank=True, db_column='order_date', null=True)),
                ('required_date', models.DateField(blank=True, db_column='required_date', null=True)),
                ('shipped_date', models.DateField(blank=True, db_column='shipped_date', null=True)),
                ('freight', models.DecimalField(blank=True, db_column='freight', decimal_places=2, max_digits=10, null=True)),
                ('ship_name', models.CharField(blank=True, db_column='ship_name', max_length=40, null=True)),
                ('ship_address', models.CharField(blank=True, db_column='ship_address', max_length=60, null=True)),
                ('ship_city', models.CharField(blank=True, db_column='ship_city', max_length=15, null=True)),
                ('ship_region', models.CharField(blank=True, db_column='ship_region', max_length=15, null=True)),
                ('ship_postal_code', models.CharField(blank=True, db_column='ship_postal_code', max_length=10, null=True)),
                ('ship_country', models.CharField(blank=True, db_column='ship_country', max_length=15, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('quantity', models.SmallIntegerField(db_column='quantity')),
                ('discount', models.FloatField(db_column='discount')),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='product_name', max_length=40)),
                ('proveedor_id', models.IntegerField(db_column='supplier_id', null=True)),
                ('categoria_id', models.IntegerField(db_column='category_id', null=True)),
                ('cantidad_por_unidad', models.CharField(db_column='quantity_per_unit', max_length=20, null=True)),
                ('precio', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('stock', models.SmallIntegerField(db_column='units_in_stock')),
                ('descontinuado', models.IntegerField(db_column='discontinued')),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(db_column='region_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='region_description', max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(db_column='shipper_id', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='company_name', max_length=40)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=24, null=True)),
            ],
            options={
                'db_table': 'shippers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(db_column='supplier_id', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='company_name', max_length=40)),
                ('contact_name', models.CharField(blank=True, db_column='contact_name', max_length=30, null=True)),
                ('contact_title', models.CharField(blank=True, db_column='contact_title', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=60, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=10, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=24, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=24, null=True)),
                ('homepage', models.TextField(blank=True, db_column='homepage', null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.CharField(db_column='territory_id', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='territory_description', max_length=50)),
            ],
            options={
                'db_table': 'territories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritory',
            fields=[
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.employee')),
            ],
            options={
                'db_table': 'employee_territories',
                'managed': False,
            },
        ),
    ]
